/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rs.ac.bg.fon.ps.view.form;

import java.awt.event.ActionListener;
import rs.ac.bg.fon.ps.constants.Constants;
import rs.ac.bg.fon.ps.domain.TrenerKluba;
import rs.ac.bg.fon.ps.view.coordinator.Coordinator;

/**
 *
 * @author Korisnik
 */
public class FrmMain extends javax.swing.JFrame {

    /**
     * Creates new form FrmMain
     */
    public FrmMain() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLogout = new javax.swing.JButton();
        lblTrener = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuItemCreateTrener = new javax.swing.JMenu();
        itemInsertTrener = new javax.swing.JMenuItem();
        menuClanovi = new javax.swing.JMenu();
        itemInsertClan = new javax.swing.JMenuItem();
        itemSearchClan = new javax.swing.JMenuItem();
        itemEditClan = new javax.swing.JMenuItem();
        itemDeleteClan = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        itemInsertProgramRada = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        itemInsertTreningGrupa = new javax.swing.JMenuItem();
        itemEditTreningGrupa = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sinergija");

        btnLogout.setText("Izloguj se");

        lblTrener.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTrener.setText("jLabel1");

        jLabel1.setText("Aktivni korisnik:");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/ac/bg/fon/ps/image/logo.png"))); // NOI18N

        menuItemCreateTrener.setText("Trener Kluba");

        itemInsertTrener.setText("Dodavanje novog trenera");
        menuItemCreateTrener.add(itemInsertTrener);

        jMenuBar1.add(menuItemCreateTrener);

        menuClanovi.setText("Clanovi Teretane");

        itemInsertClan.setText("Dodavanje novog clana");
        menuClanovi.add(itemInsertClan);

        itemSearchClan.setText("Pretraga clanova");
        menuClanovi.add(itemSearchClan);

        itemEditClan.setText("Izmena podataka clanova");
        menuClanovi.add(itemEditClan);

        itemDeleteClan.setText("Brisanje clanova");
        menuClanovi.add(itemDeleteClan);

        jMenuBar1.add(menuClanovi);

        jMenu3.setText("Program Rada");

        itemInsertProgramRada.setText("Dodavanje novog programa");
        jMenu3.add(itemInsertProgramRada);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Trening Grupe");

        itemInsertTreningGrupa.setText("Dodavanje nove grupe");
        jMenu4.add(itemInsertTreningGrupa);

        itemEditTreningGrupa.setText("Izmena trening grupe");
        jMenu4.add(itemEditTreningGrupa);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(lblTrener, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(115, 115, 115))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jLabel2)
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(lblTrener, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JMenuItem itemDeleteClan;
    private javax.swing.JMenuItem itemEditClan;
    private javax.swing.JMenuItem itemEditTreningGrupa;
    private javax.swing.JMenuItem itemInsertClan;
    private javax.swing.JMenuItem itemInsertProgramRada;
    private javax.swing.JMenuItem itemInsertTrener;
    private javax.swing.JMenuItem itemInsertTreningGrupa;
    private javax.swing.JMenuItem itemSearchClan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblTrener;
    private javax.swing.JMenu menuClanovi;
    private javax.swing.JMenu menuItemCreateTrener;
    // End of variables declaration//GEN-END:variables

    public void setLblTrener() {
        TrenerKluba trener = (TrenerKluba) Coordinator.getInstance().getParam(Constants.CURRENT_USER);
        lblTrener.setText(trener.toString());
    }

    public void itemInsertTrenerActionListener(ActionListener actionListener) {
        itemInsertTrener.addActionListener(actionListener);
    }

    public void itemInsertClanAddActionListener(ActionListener actionListener) {
        itemInsertClan.addActionListener(actionListener);
    }

    public void itemEditClanAddActionListener(ActionListener actionListener) {
        itemEditClan.addActionListener(actionListener);
    }

    public void itemSearchClanAddActionListener(ActionListener actionListener) {
        itemSearchClan.addActionListener(actionListener);
    }

    public void itemDeleteClanCreateAddActionListener(ActionListener actionListener) {
        itemDeleteClan.addActionListener(actionListener);
    }

    public void itemInsertProgramRadaDeleteAddActionListener(ActionListener actionListener) {
        itemInsertProgramRada.addActionListener(actionListener);
    }

    public void itemInsertTreningGrupaAddActionListener(ActionListener actionListener) {
        itemInsertTreningGrupa.addActionListener(actionListener);
    }

    public void itemEditTreningGrupaAddActionListener(ActionListener actionListener) {
        itemEditTreningGrupa.addActionListener(actionListener);
    }
    
    public void addButtonLogoutActionListener(ActionListener actionListener){
    btnLogout.addActionListener(actionListener);
    }

}
